### ISSUE TITLE
Broken deploys (CloudFront?)

### ISSUE THREAD

**Issue by skalee** [geolexica/osgeo.geolexica.org#29]
Deploying to staging does not fully update the site. For example, content of https://osgeo.geolexica.org/assets/js/concept-search-worker.js script stays the same, even though there were changes in the source code, and they are reflected in local Jekyll builds. Only OSGeo staging is affected, whereas TC211 staging updates as expected.

My belief is that deploy configuration is broken, that is some of these secrets hold incorrect values:

https://github.com/geolexica/osgeo.geolexica.org/blob/d3059a71c741d3663b7f4afff358d7595e2e1d59/.github/workflows/deploy-staging.yml#L42-L48

Probably for @ronaldtse.

**Comment by ronaldtse** [comment]
Will check later tonight. Nothing has changed in this regard though...

**Comment by skalee** [comment]
Oh I know what's happening!

- staging branch is deployed to https://osgeodev.geolexica.org
- deploys from master are disabled, but normally it is deployed to https://osgeo.geolexica.org
- link on the https://www.geolexica.org/ site roster points to https://osgeo.geolexica.org (master), which is never deployed under the current setup

The configuration is correct, and the staging site is updated correctly. It was just me who was checking the outdated master site instead of the up-to-date staging one. Well, I always forget the address, so I am using roster page instead.

That leads to another thing though.  Perhaps we should update link on roster page so that it points to a staging site, shouldn't we?  A link on that page says "work in progress", so that may have sense IMO.  Or perhaps we should re-enable deploys from master?  @ronaldtse?

**Comment by ronaldtse** [comment]
@skalee I believe @ReesePlews still prefers to keep the production site not being "official" because we don't want people to use those terms that are not yet "officiated". Perhaps we can deploy the master site to the staging for now?

**Comment by skalee** [comment]
Sure we can deploy from master to staging, and I'll do the same for IEV demo. I just wanted to clarify what site geolexica.org roster should link to.

**Comment by skalee** [comment]
Or… Let's keep deploys as they are. It's seldom useful, but sometimes it is when we want to deploy something very temporary.

Though I'm going to re-enable master branch on IEV site, just with disabled deploys.

**Comment by ronaldtse** [comment]
It actually sounds like we should update documentation — I forgot this myself at least once too :-)
