### ISSUE TITLE
(URGENT) Enable SKOS output

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/osgeo.geolexica.org#31]
@skalee we need to deploy the SKOS and TBX output from this site ASAP. Thanks.

**Comment by ronaldtse** [comment]
Ping @skalee

**Comment by ronaldtse** [comment]
@skalee I see that JSON and TBX are enabled, but not TTL and JSON-LD which contains SKOS...?

<img width="664" alt="Screen Shot 2020-09-30 at 10 10 38 AM" src="https://user-images.githubusercontent.com/11865/94635415-3131d000-0305-11eb-9a38-950bd3fed835.png">

**Comment by ronaldtse** [comment]
Ping @skalee

**Comment by skalee** [comment]
Neither do I. This is quite surprising.

**Comment by skalee** [comment]
Oh, actually it's there on https://osgeodev.geolexica.org/concepts/1/.

> ![Zrzut ekranu 2020-10-09 o 23 18 22](https://user-images.githubusercontent.com/154287/95632636-61f0d280-0a86-11eb-8035-382b2b960ac1.png)

**Comment by ronaldtse** [comment]
Thank you @skalee !
