### ISSUE TITLE
Import glossary data from Google Sheet

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/osgeo.geolexica.org#5]
https://docs.google.com/spreadsheets/u/1/d/19tulyAEDN5Q5n-u_jlmXIKQjPI2Lwv6fh5Orad1mz1I/edit#gid=0

**Comment by ronaldtse** [comment]
Better yet, create an automated script to import on changes...? Instability...

**Comment by skalee** [comment]
@ronaldtse Is this issue valid any longer?

**Comment by ronaldtse** [comment]
@skalee the sheet to import has changed. It should now be:
https://docs.google.com/spreadsheets/d/1keonRLT3chmqlRZsMMF9UaCI_vzNEHmJx6t9LB3jBjM/edit#gid=1083334541

There are now 4 sheets:
<img width="921" alt="Screen Shot 2020-11-02 at 3 38 12 PM" src="https://user-images.githubusercontent.com/11865/97841744-6c1e8d80-1d21-11eb-8644-b7cedc62bed4.png">

* `abbre working_sheet`: each of these should be imported as an "abbreviation"
* `terms - proposed`: import as terms
* `terms - more discussion needed`: no need for import
* `domains`: no need for import

**Comment by skalee** [comment]
@ronaldtse I suppose spreadsheets are not a long-term solution for OSGeo? I'm asking because there are some changes to be made and I need to decide quick vs easy to use & maintainable.

**Comment by ronaldtse** [comment]
@skalee it will be a one time import and they will be maintained in Glossarist from then on.

**Comment by ronaldtse** [comment]
We need to complete the import before Thursday.

**Comment by skalee** [comment]
I need clarifications on columns.

### abbreviations working_sheet:

- term – column A
- domain – column E
- definition – G
- source – H
- entry status – J

All imported literally as they are in spreadsheet.

### proposed terms sheet:

- term – A, B, C
- domain – ?
- comments – E
- source – ?
- entry status – ?

All imported literally as they are in spreadsheet.

---

What to do with the remaining columns?

**Comment by ronaldtse** [comment]
> ### abbreviations working_sheet:
> * term – column A

Yes. Mark the term as an abbreviation.

> * domain – column E

Drop.

> * definition – G

Yes.
> * source – H

Yes.
> * entry status – J

Drop.

> ### proposed terms sheet:
> * term – A, B, C

Yes.
> * domain – ?

None.
> * comments – E

Drop.

> * source – ?
Column H.

> * entry status – ?

None.

> What to do with the remaining columns?

Drop.

**Comment by skalee** [comment]
Should I drop comments from table "proposed" and keep ones from table "abbreviations", or should I drop them all? I thought they were supposed to be imported as notes or something (https://github.com/geolexica/osgeo-glossary/issues/9)?

**Comment by skalee** [comment]
```
  terms:
  - type: expression
    designation: 3DEP
    normative_status: 
```

Could anyone help me what values are acceptable in `normative_status` field? I recall we have some nice UML diagram, but can't find it. Also, `type` should be `expression` in every case here, shouldn't it?

**Comment by skalee** [comment]
In "proposed" sheet, how to parse source (column H) which looks like following:

```
ISO 19115-1:2014, 4.10, modified — An admitted term from OSGeo has been added.
```

I mean:

- which part is ref, I suppose `ISO 19115-1:2014`?
- which is clause, I suppose `4.10`?
- what to do with the rest of the text

Also how to interpret following sources:

- `GVSIG_1-0_2011`
- `GEONETWOK_OPENSOURCE`

**Comment by ronaldtse** [comment]
> Should I drop comments from table "proposed" and keep ones from table "abbreviations", or should I drop them all?  

Actually, yes you're right. Let's keep the comments from "abbreviations".

> Could anyone help me what values are acceptable in `normative_status` field? I recall we have some nice UML diagram, but can't find it. 

`normative_status`: `"valid"`, just like in
https://github.com/glossarist/iev-data/blob/77902db5868f0436a9b030dc2b7a4e442e79c283/lib/iev/termbase/term.rb#L175

> Also, type should be `expression` in every case here, shouldn't it?

Yes. For Abbreviations we should also set `abbrev` to true.

> In "proposed" sheet, how to parse source (column H) which looks like following:
> 
> ```
> ISO 19115-1:2014, 4.10, modified — An admitted term from OSGeo has been added.
> ```
> 
> I mean:
> 
> * which part is ref, I suppose `ISO 19115-1:2014`?

Yes.

> * which is clause, I suppose `4.10`?

Yes.

> * what to do with the rest of the text

Ping @strogonoff - In ISO terms it is possible to "modify" the definition. We need somewhere to store this.

@skalee perhaps we can store it in a new key associated with the source information?

> Also how to interpret following sources:
> 
> * `GVSIG_1-0_2011`
> * `GEONETWOK_OPENSOURCE`

Just include them as text for now as source. We will edit them afterwards via Glossarist.

**Comment by skalee** [comment]
ok, then:

```yaml
  authoritative_source:
    ref: 'ISO 19115-1:2014'
    clause: '4.10'
    comment: 'modified — An admitted term from OSGeo has been added'
```

With the last one for future use. @strogonoff you're okay with that?

**Comment by skalee** [comment]
I try to maintain alphabetical ordering of terms, because it used to be like that before. This raises two questions though:

- Because some terms are added and some other removed/renamed, some concepts will not maintain their previous ids. Is it okay?
- If given designation is defined many times (e.g. "ebRIM": [106](https://osgeo.geolexica.org/concepts/106/), [107](https://osgeo.geolexica.org/concepts/107/), [108](https://osgeo.geolexica.org/concepts/108/)), is it okay to order them randomly?

BTW, should I mark duplicated concepts somehow? Like column B "is duplicate?" in the spreadsheet?

**Comment by skalee** [comment]
> `normative_status`: `"valid"`, just like in
> https://github.com/glossarist/iev-data/blob/77902db5868f0436a9b030dc2b7a4e442e79c283/lib/iev/termbase/term.rb#L175

Hmm, are you sure? I've just used grep against other glossaries and the only values in use are:

in TC211:

```
normative_status: admitted
normative_status: null
normative_status: preferred
```

in IEV:

```
normative_status: deprecated
normative_status: preferred
```

Formerly this field was always blank for OSGeo, probably due to bug.

**Comment by skalee** [comment]
~Deployed to staging: https://osgeodev.geolexica.org/~. Above questions remain valid. Note: authoritative sources need some more tweaking.

**Comment by ronaldtse** [comment]
@skalee then I was mistaken. Let's make the `normative_status` as `preferred`. Thanks.

**Comment by ronaldtse** [comment]
> I try to maintain alphabetical ordering of terms, because it used to be like that before. This raises two questions though:
> 
> * Because some terms are added and some other removed/renamed, some concepts will not maintain their previous ids. Is it okay?
> * If given designation is defined many times (e.g. "ebRIM": [106](https://osgeo.geolexica.org/concepts/106/), [107](https://osgeo.geolexica.org/concepts/107/), [108](https://osgeo.geolexica.org/concepts/108/)), is it okay to order them randomly?
> 
> BTW, should I mark duplicated concepts somehow? Like column B "is duplicate?" in the spreadsheet?

We are trying to consolidate the duplicates in the spreadsheet (so at import there should not be duplicates), so it shouldn't be important.

**Comment by skalee** [comment]
Thanks. That means that this is not the spreadsheets' final form yet, correct?

The "proposed" spreadsheet contains column G "Definition (original)" with quite lot information. Should I drop it or import as comment or something?

**Comment by skalee** [comment]
Deployed once again to https://osgeodev.geolexica.org/. Apart from question in my previous comment, it should be fine.

**Comment by ronaldtse** [comment]
@skalee quick note that we should now activate the production site, OSGeo.geolexica.com. Thanks!

**Comment by skalee** [comment]
OSGeo.geolexica.org is online for several days (see #32). Perhaps you mean that I should deploy recent changes to OSGeo.geolexica.org?

Also, should I really drop column G "Definition (original)" from the "proposed" spreadsheet? I could import that as comments or something. I can do the same with J "Proposed action for OSGEO repository". Comments are in array anyway.

Also, no more changes will be made to this spreadsheets? No dupes removal, nothing like that, correct?

**Comment by ronaldtse** [comment]
> OSGeo.geolexica.org is online for several days (see #32). Perhaps you mean that I should deploy recent changes to OSGeo.geolexica.org?

Yes please! Let's deploy to production by default now.

> Also, should I really drop column G "Definition (original)" from the "proposed" spreadsheet? I could import that as comments or something. I can do the same with J "Proposed action for OSGEO repository". Comments are in array anyway.

Yes, can import them as comments.

> Also, no more changes will be made to this spreadsheets? No dupes removal, nothing like that, correct?

There may be some changes, but will let you know.

**Comment by skalee** [comment]
> > Also, no more changes will be made to this spreadsheets? No dupes removal, nothing like that, correct?
> There may be some changes, but will let you know.

I was asking because some changes were easier to do manually. I am keeping a proper patch just in case I'll have to re-apply it.

**Comment by skalee** [comment]
Deployed to production & staging.

----

FYI @ronaldtse, comments are actually **visible** if you download JSON or YAML, e.g. https://osgeodev.geolexica.org/api/concepts/57.json.

**Comment by ronaldtse** [comment]
Thank you @skalee !
